# Generated by Django 5.1.6 on 2025-04-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_alter_task_descriptions_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='descriptions',
            field=models.TextField(),
        ),
    ]
